www/Dosaaf/Dosaaf/Components/EducationOnlineViewComponent.cs
using Dosaaf.Models;
using Dosaaf.Services;
using Microsoft.AspNetCore.Mvc;

namespace Dosaaf.Components
{
    public class EducationOnlineViewComponent: ViewComponent
    {
        private readonly ApplicationContext _db;
        public EducationOnlineViewComponent(ApplicationContext db)
        {
            _db = db;
        }
        public IViewComponentResult Invoke()
        {
            IEnumerable<OnlineEducation> onlineEducations = _db.OnlineEducations.ToList();
            return View("EducationOnline", onlineEducations);
        }
    }
}

www/Dosaaf/Dosaaf/Components/EducationViewComponent.cs
using Dosaaf.Models;
using Dosaaf.Services;
using Microsoft.AspNetCore.Mvc;

namespace Dosaaf.Components
{
    public class EducationViewComponent: ViewComponent
    {
        private readonly ApplicationContext _db;
        public EducationViewComponent(ApplicationContext db)
        {
            _db = db;
        }

        public IViewComponentResult Invoke()
        {
            IEnumerable<Education> educations = _db.Educations.ToList();
            return View("Education", educations);
        }
    }
}

www/Dosaaf/Dosaaf/Components/ReviewPanelViewComponent.cs
using Dosaaf.Models;
using Dosaaf.Services;
using Microsoft.AspNetCore.Mvc;

namespace Dosaaf.Components
{
    public class ReviewPanelViewComponent: ViewComponent
    {
        private readonly ApplicationContext _db;
        public ReviewPanelViewComponent(ApplicationContext db)
        {
            _db = db;
        }

        public IViewComponentResult Invoke()
        {
            IEnumerable<Review> reviews = _db.Reviews.ToList();

            return View("ReviewPanel", reviews);
        }
    }
}

www/Dosaaf/Dosaaf/Controllers/AdminPanelController.cs
using Dosaaf.Models;
using Dosaaf.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Dosaaf.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly IEncryptionService _encryptionService;

        public AdminPanelController(ApplicationContext db, IEncryptionService encryptionService)
        {
            _db = db;
            _encryptionService = encryptionService;
        }

        [Route("AdminPanel/Index")]
        public IActionResult Index()
        {
            return View();
        }
      
        [Route("AdminPanel/Management")]
        public IActionResult Management()
        {
            if (Request.Cookies.Keys.FirstOrDefault(x => x == "authKey") == null)
            {
                Console.WriteLine("yes");
                return Redirect("Index");
            }

            return View();
        }

        [HttpPost]
        public IActionResult DeleteReview(string Id)
        {
            var review = _db.Reviews.FirstOrDefault(
                x => x.Id == int.Parse(Id)
            );
            _db.Reviews.Remove(review!);
            _db.SaveChanges();

            return Redirect("Management");
        }

        [HttpPost]
        public IActionResult Login(Admin admin)
        {
            Admin? person = _db.Admins.FirstOrDefault(
                x => 
                x.Name == admin.Name && 
                x.Password == _encryptionService.Base64Encode(admin.Password!)
            );

            if (person is null)
            {
                return Redirect("Index");
            }    
                
            Response.Cookies.Append(
                "authKey",
                _encryptionService.Base64Encode(admin.Name!)
            );
            return Redirect("Management");
        }
    }
}

www/Dosaaf/Dosaaf/Views/AdminPanel/Index.cshtml
@addTagHelper *, Dosaaf
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "- Админ панель. Логин";
}
@model Dosaaf.Models.Admin

<div id="admin-page-login">
    <h1>Админ панель</h1>
    <form class="send-form" method="post" asp-action="Login" asp-controller="AdminPanel">
        <div class="application-point">
            <label>Login</label>
            <input type="text" asp-for="Name" />
        </div>
        <div class="application-point">
            <label>Password</label>
            <input type="password" asp-for="Password" />
        </div>
        <div class="application-point">
            <input class="submit-changes" type="submit" value="Login" />
        </div>
    </form>
</div>

www/Dosaaf/Dosaaf/Views/AdminPanel/Management.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "- Админ панель";
}

<div id="management-section">
    @await Component.InvokeAsync("ReviewPanel")
    @await Component.InvokeAsync("Education")
    @await Component.InvokeAsync("EducationOnline")
</div>