www/Dosaaf/Dosaaf/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Dosaaf.Components
{
    public class HeaderViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            Dictionary<string, string> pairsOfPages = new Dictionary<string, string>
            {
                { "/", "Главная" },
                { "Tips", "Сведения" },
                { "Price", "Цены" },
                { "Contacts", "Контакты" },
                { "OnlineEducation", "Онлайн обучение" },
                { "Feedback", "Отзывы" }
            };

            return View("Header", pairsOfPages);
        }
    }
}

www/Dosaaf/Dosaaf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!--links-->
    <link rel="icon" type="image/x-icon" href="~/static/Icons/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="~/static/css/styles.css" />
    <link rel="stylesheet" type="text/css" href="~/static/css/fonts.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--scripts-->
    <script src="https://api-maps.yandex.ru/2.1/?apikey=940c7c55-3f22-4cb6-9033-98686160c335&lang=ru_RU" type="text/javascript"></script>
    <script src="https://kit.fontawesome.com/2a7d351d8a.js" crossorigin="anonymous"></script>
    <script src="~/static/js/script.js" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
    <!--meta tags-->
    <meta name="description" content="Учебный Центр Гайского ДОСААФ – это профессиональная образовательная организация, занимающаяся профессиональной подготовкой водителей транспортных средств категорий «В», «А» , «М», «СЕ», а также переподготовкой водителей транспортных средств с категории «В» на категорию «С», с категории «С» на категорию «В», с категории «С» на категорию «D». ... 462630, Оренбургская область, г. Гай, ул. Молодежная, д.4А." />
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="Автошкола, ДОСААФ Гай, Автошкола ДОСААФ Гай, Учебный Центр Гайского ДОСААФ" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="ZMQP Project" />
    <meta name="copyright" lang="ru" content="Учебный Центр Гайского ДОСААФ" />
    <meta http-equiv="content-language" content="ru" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>Автошкола Досааф @ViewBag.Title</title>
</head>
<body>
    <div id="wrapper">
        @await Component.InvokeAsync("Header")
        <div id="main">
            @RenderBody()
        </div>
    </div>
    <div id="footer">
        @await Component.InvokeAsync("Header")
    </div>
    <script>
        let button = document.querySelector(".hamburger-menu-button");
        let menu = document.querySelector(".hamburger-menu");

        button.addEventListener('click', function() {
            menu.classList.toggle('active');
        })
    </script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
            (function(m, e, t, r, i, k, a) {
                m[i] = m[i] || function() { (m[i].a = m[i].a || []).push(arguments) };
                var z = null; m[i].l = 1 * new Date();
                for (var j = 0; j < document.scripts.length; j++) { if (document.scripts[j].src === r) { return; } }
                k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
            })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(90074318, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/90074318" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>